server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8001/
          predicates:
            - Path=/first-service/**

        - id: jwt-service
          uri: http://localhost:8082/
          predicates:
            - Path=/jwt-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: jwt-service
          uri: http://localhost:8082/
          predicates:
            - Path=/jwt-service/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: shop-service
          uri: http://localhost:8083/
          predicates:
            - Path=/shop-service/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: shop-service
          uri: http://localhost:8083/
          predicates:
            - Path=/shop-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

token:
  secret: ${JWT_SECRET}
  expiration-time: 36000000000 # 만료 시간을 초 단위로 설정 (예: 1시간)


logging:
  level:
    root: INFO
    com:
      example:
        jwtjwt: TRACE





